title: Zafarullah Mahmood
email: zafarullahmahmood@gmail.com
description: Blogs by Zafarullah Mahmood (zaffnet) | zafar@zafarmahmood.com
baseurl: ""
url: "https://zafarmahmood.com"
github_username:  zaffnet
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-gist
exclude:
  - vendor/
  - vendor/bundle/
  - node_modules/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
